AVAIABLE_API = {
    'verify':
    'verify',
    'bind':
    'bind',
    'release':
    'release',
    'count_message':
     'countMessage',
    'fetch_message':
    'fetchMessage',
    'fetch_latest_message':
    'fetchLatestMessage',
    'peek_message':
    'peekMessage',
    'peek_latest_message':
    'peekLatestMessage',
    'about':
    'about',
    'message_from_id':
    'messageFromId',
    'friend_list':
    'friendList',
    'group_list':
    'groupList',
    'member_list':
    'memberList',
    'bot_profile':
    'botProfile',
    'friend_profile':
    'friendProfile',
    'member_profile':
    'memberProfile',
    'send_friend_message':
    'sendFriendMessage',
    'send_group_message':
    'sendGroupMessage',
    'send_temp_message':
    'sendTempMessage',
    'send_nudge':
    'sendNudge',
    'recall':
    'recall',
    'file_list':
    'file/list',
    'file_info':
    'file/info',
    'file_mkdir':
    'file/mkdir',
    'file_delete':
    'file/delete',
    'file_move':
    'file/move',
    'file_rename':
    'file/rename',
    'upload_image':
    'uploadImage',
    'upload_voice':
    'uploadVoice',
    'delete_friend':
    'deleteFriend',
    'mute':
    'mute',
    'unmute':
    'unmute',
    'kick':
    'kick',
    'quit':
    'quit',
    'mute_all':
    'muteAll',
    'unmute_all':
    'unmuteAll',
    'set_essence':
    'setEssence',
    'group_config':
    'groupConfig',
    'member_info':
    'memberInfo',
    'resp_new_friend_request_event':
    'resp/newFriendRequestEvent',
    'resp_member_join_request_event':
    'resp/memberJoinRequestEvent',
    'resp_bot_invited_join_group_request_event':
    'resp/botInvitedJoinGroupRequestEvent'
}
